import React from 'react';
import './App.css';
// import Cell from './Cell';

/* 
    TODO
    * clean up
    * save whole image/print
    * have some on the site to be able to modify
    * styled components?
    * random animal generator
    * be able to select all spans of a certain color on the page
    * styling
*/

class App extends React.Component {
    constructor() {
        super();
        this.state = {
            rows: 23,
            columns: 23,
            selectedColor: "#ffffff",
            cells: [],
            storedColors: [],
            storedImages: [ 
                {
                    "lion": {
                        cells: [
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#000000"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#000000"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#000000"},
                        {color: "#000000"},
                        {color: "#000000"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#f9f343"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#000000"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#fffbf0"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#f9f343"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#f9f343"},
                        {color: "#fffbf0"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#f9f343"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#ec9e18"},
                        {color: "#fffbf0"},
                        {color: "#ec9e18"},
                        {color: "#fffbf0"},
                        {color: "#ec9e18"},
                        {color: "#fffbf0"},
                        {color: "#ec9e18"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"},
                        {color: "#a00d0d"}
                        ],
                        storedColors: [
                        "#f9f343",
                        "#ec9e18",
                        "#a00d0d",
                        "#000000",
                        "#fffbf0"
                        ],
                  }
                },
                {
                    "panda": {
                        cells: [
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#7dbdd8"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#7dbdd8"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#000000"},
                          {color: "#ffffff"},
                          {color: "#ffffff"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"},
                          {color: "#4a3e74"}
                        ],
                        storedColors: [
                          "#4a3e74",
                          "#000000",
                          "#ffffff",
                          "#7dbdd8"
                        ],
                      }
                }

            ],
            name: "",
        }

        this.handleRowChange = this.handleRowChange.bind(this);
        this.handleColChange = this.handleColChange.bind(this);
        this.handleColorInputChange = this.handleColorInputChange.bind(this);
        this.updateGrid = this.updateGrid.bind(this);
        this.changeCellColor = this.changeCellColor.bind(this);
        this.applyToAll = this.applyToAll.bind(this);
        this.storeColor = this.storeColor.bind(this);
        this.setColor = this.setColor.bind(this);
        this.addImage = this.addImage.bind(this);
        this.addName = this.addName.bind(this);
        this.applyStoredImage = this.applyStoredImage.bind(this);
    }

    updateGrid(param) {
        let color = this.state.color || "#fff";
        let rows = this.state.rows;
        let columns = this.state.columns;
        if (param) {
            switch(Object.keys(param)[0]) {
                case "color":
                    color = Object.values(param)[0];
                    break;
                case "rows":
                    rows = Object.values(param)[0];
                    break;
                case "columns":
                    columns = Object.values(param)[0];
                    break;
                default:
                    break;
            }
        }

        let grid = [];
        for (let i=0; i < rows; i++) {
            for (let j=0; j < columns; j++) {
                grid.push({ color: color});
            }
        }
        this.setState({ cells: grid })
    }

    componentDidMount() {
        this.updateGrid();
    }

    handleRowChange(event) {
        this.setState({ rows: parseInt(event.target.value) });
        this.updateGrid({ "rows": parseInt(event.target.value) });
    }

    handleColChange(event) {
        this.setState({ columns: parseInt(event.target.value) });
        this.updateGrid({ "columns": parseInt(event.target.value) });
    }

    handleColorInputChange(event) {
        this.setState({ selectedColor: event.target.value })
    }

    changeCellColor(i) {
        let cells = [...this.state.cells];
        let changedCell = {...cells[i]};
        changedCell.color = this.state.selectedColor;
        cells[i] = changedCell;
        this.setState({ cells: cells })
    }

    applyToAll(color) {
        this.updateGrid({ "color": color });
    }

    storeColor() {
        const selectedColor = this.state.selectedColor;
        let listOfStored = [...this.state.storedColors];
        listOfStored = listOfStored.concat(selectedColor);
        this.setState({ storedColors: listOfStored })
    }

    setColor(color) {
        this.setState({ selectedColor: color })
    }

    addName(event) {
        this.setState({ name: event.target.value })
    }

    addImage() {
        if (this.state.name) {
            let images = [...this.state.storedImages];
            const name = this.state.name;
            const cells = this.state.cells;
            let newImage = {}
            newImage[name] = cells;
            images = images.concat(newImage);
            this.setState({ storedImages: images });
        }
    }

    applyStoredImage(image) {
        const cells = Object.values(image)[0].cells;
        const colors = Object.values(image)[0].storedColors;
        this.setState({ cells: cells, storedColors: colors })
    }

    render() {
        return (
            <div className="App">

                <label>How many rows?</label>
                <input type="number" value={this.state.rows} onChange={this.handleRowChange}></input>
                <label>How many columns?</label>
                <input type="number" value={this.state.columns} onChange={this.handleColChange}></input>
                <label>What color?</label>
                <input type="color" value={this.state.selectedColor} onChange={this.handleColorInputChange}></input>
                <label>Name</label>
                <input type="text" onChange={this.addName}></input>
                <button onClick={() => this.applyToAll("#fff")}>Clear all</button>
                <button onClick={() => this.applyToAll(this.state.selectedColor)}>Apply to all</button>
                <button onClick={this.storeColor}>Store color</button>
                <button onClick={this.addImage}>Add image</button>

                <ul>
                    {this.state.storedColors.map((color, index) => 
                        <li style={{ color: color }} key={index} onClick={() => this.setColor(color)}>{index}</li>
                    )}
                </ul>
                <ul>
                    {this.state.storedImages.map((image, index) => 
                        <button key={index} onClick={() => this.applyStoredImage(image)}>{Object.keys(image)[0]}</button>
                    )}
                </ul>

                <div className="grid" style={{"--rows": this.state.rows, "--cols": this.state.columns}}>
                    {this.state.cells.map((item, index) => 
                        <span className="cell" key={index} style={{ backgroundColor: item.color }} onClick={() => this.changeCellColor(index)}></span>)
                    }
                </div>
            </div>
        );
    }
}

export default App;
